version: '3.9'

services:
  api:
    build: .
    ports:
      - '8080:8080'
  
  db:
    image: 'postgres:14-alpine'
    
    environment:
      POSTGRES_PASSWORD: 'admin1234'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'reservations'