version: "3.1"

services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin1234"
      POSTGRES_DB: "restaurant"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
